//go:build linux && cgo && !agent

// Code generated by generate-database from the incus project - DO NOT EDIT.

package cluster

var networkPeerCreate = RegisterStmt(`
INSERT INTO networks_peers (network_id, name, description, type)
  VALUES (?, ?, ?, ?)
`)

var networkPeerID = RegisterStmt(`
SELECT networks_peers.id FROM networks_peers
  WHERE networks_peers.network_id = ?
`)
